packages:
  - schema
  - server
  - admin
  - ui
  - e2e
  - bots

ignoredBuiltDependencies:
  - "@asyncapi/cli"
  - "@hyperjump/json-pointer"
  - "@hyperjump/json-schema"
  - "@hyperjump/json-schema-core"
  - "@hyperjump/pact"
  - esbuild
  - protobufjs
  - puppeteer
  - unrs-resolver
  - yarn

onlyBuiltDependencies:
  - better-sqlite3
